version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ipl_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Subhro@02
      POSTGRES_DB: ipl_auction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ipl_redis
    ports:
      - "6379:6379"
    # Keep data on disk so we don't lose state if container restarts
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data: